name: build/release

on:
  push:
    branches: master
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: npm install
        run: npm ci

      - name: build
        run: npm run build

      - name: release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        run: npm publish
