name: build/release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: build
        run: npm ci
        run: npm build

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: build
        run: npm ci
        run: npm build

      - name: release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: "npm publish"
