name: build/release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: npm install
        run: npm ci

      - name: build
        run: npm run build

      - name: release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
